// Generated by CoffeeScript 1.6.2
var promptForTile1, promptForTile2, stdin;

stdin = process.openStdin();

stdin.setEncoding('utf8');

promptForTile1 = function() {
  var inputCallback;

  console.log("Введите координаты первого тайла.");
  return inputCallback = function(input) {
    if (strToCoordinate(input)) {
      return promptForTile2;
    }
  };
};

promptForTile2 = function() {
  var inputCallback;

  console.log("Введите координаты второго тайла.");
  return inputCallback = function(input) {
    if (strToCoordinate(input)) {
      console.log("Меняем местами тайлы... готово!");
      return promptForTile1();
    }
  };
};

stdin.on('data', function(input) {
  return inputCallback(input);
});
